# Generated by Django 5.0.2 on 2024-03-18 15:29

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=255, validators=[store.validators.customer_phone_validate], verbose_name='Номер телефона'),
        ),
    ]
